Move to production
akucintavalent/covid-19-stats pull request #2
Opened 2022-02-01 23:32 UTC by akucintavalent

This is the solution to [React solo capstone project](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md).

Here is a brief description of the project: https://www.loom.com/share/649049706e114c808bb7f50cd7935d6b

In this pull request I did:
- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions and reducers in React.

I used Narrativa API: COVID-19 data. 

The app looks like this:
### Earth
> <img width="295" alt="earth" src="https://user-images.githubusercontent.com/87897753/152068840-ed4189c7-284e-4f0a-96f4-2f7b5de16b8d.png">
### Continent
> <img width="294" alt="continent" src="https://user-images.githubusercontent.com/87897753/152068864-f50a7d14-7fb1-464d-bc35-03de66d592ef.png">
### Country
> <img width="294" alt="country" src="https://user-images.githubusercontent.com/87897753/152068901-38c0e116-4517-4404-a8d7-ddd0218e7a20.png">

The link to demo: https://keen-wright-b70cfc.netlify.app/

2022-02-01 23:57 UTC, BrianSammit requested changes
# CHANGES REQUIRED 🔴 🛑
Hello <STUDENT_MENTION>, great job you are doing so far in this project. 💯

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 

However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️
See my inline comment to know what changes are needed. 👇 👀 

Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

![cat](https://user-images.githubusercontent.com/64173189/131593916-14c184cb-b5af-40f7-8fba-779155f154cb.gif)


**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-01 23:57 UTC, BrianSammit commented on README.md
- [ ] It would be better if you give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

Please add this 😄 🛠️

2022-02-01 23:57 UTC, BrianSammit commented on README.md
- [ ] It would be better if you add the live version of the app as one of the requirements for this capstone. 

💪 👍

2022-02-02 00:13 UTC, omar-labana commented
Hi @akucintavalent, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 00:15 UTC, merged